### PR TITLE
Adds procs to call to gather extra log data for a controller

### PR DESCRIPTION
**Pull request by gstark**
Allows a controller to inject additional summary data to the completion of a controller action.

I didn't add any tests for this as I didn't see any in the project. Let me know if they are needed.

### CODE REVIEW

**Comment by reidmorrison** [comment]
Using the example, would you like the user id added to every log entry for the rails request?
I.e. Something similar to the Rails 'config.log_tags'

**Comment by gstark** [comment]
Rails provides a way to add extra information to the `payload` (via `append_info_to_payload`)

Perhaps my example in the code comments isn't the best. Really I'm looking for a way to add custom data we'd like to associate to the controller request itself. This avoids having to post-process associate the data based on some correlating data field (uuid, etc.)

Also `log_tags` seems to only have reference to the request object.

This is similar to `custom_options` feature in `lograge` which also uses the ability to add arbitrary data to the `payload` and then extract that into the log message.

**Comment by reidmorrison** [comment]
Using the example:

~~~ruby
class ThingController
  private

  def append_info_to_payload(payload)
    super
    payload[:user_id] = 42 # or whatever fetches your user_id
  end
end

config.rails_semantic_logger.action_controller_extra_log_procs << proc do |payload, log|
  log[:user_id] = payload[:user_id] if payload[:user_id]
end
~~~

I changed the code to switch from a whitelist approach to rather use a blacklist approach so that any data added in `append_info_to_payload` is automatically picked up. Per this new commit https://github.com/rocketjob/rails_semantic_logger/commit/73398314c2fd83bfe42239b49bb7869527f87091

So to get the above to work, we now only need:
~~~ruby
class ThingController
  private

  def append_info_to_payload(payload)
    super
    payload[:user_id] = 42 # or whatever fetches your user_id
  end
end
~~~

It will now log the `user_id` automatically without having to register a Proc.

If procs are still useful for other reasons, we can still add them.

**Comment by reidmorrison** [comment]
BTW, I would love to have tests for the Railtie. I have not found any examples on how to test railties. For now I manually have to test it before every release.

**Comment by gstark** [comment]
Closing this since 73398314c2fd83bfe42239b49bb7869527f87091 resolves it by adding all the payload elements.

Also I think most tests for things like this are done by adding a dummy app to the test suite. Then you invoke requests to it and inspect the side effects or results.

**Pull request closed without merging**
